---
- name: "Run ci/playbooks/run-doc.yml"
  hosts: controller
  gather_facts: true
  tasks:
    - name: Build doc
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: make docs
