---
cifmw_baremetal_hosts:
  compute-0:
    connection: "ipmi://10.9.20.141"
    boot_mode: UEFI
    nics:
      - mac: "E4:43:4B:4C:11:97"
        network: provision
    credentials_file: "/home/zuul/src/config/idrac_access.yaml"
